// ACS Datamodel Constants
ACS.mConst = {
	// model
	MODEL_DEFAULTCOMPONENTCOLLECTION: 'defaultComponentCollection.abd',
	// visualAreaMarker
	VISUALAREAMARKER_BGCOLOR: 'rgba(0, 0, 255, 0.9)',
	VISUALAREAMARKER_BORDERCOLOR: 'rgba(0, 0, 255, 0)',
	// modelGUI
	MODELGUI_DECORATION: true,
	MODELGUI_FULLSCREEN: false,
	MODELGUI_ALWAYSONTOP: false,
	MODELGUI_TOSYSTEMTRAY: false,
	MODELGUI_SHOWCONTROLPANEL: true,
	MODELGUI_AREGUIWINDOW_X: 0,
	MODELGUI_AREGUIWINDOW_Y: 0,
	MODELGUI_AREGUIWINDOW_WIDTH: 1920,
	MODELGUI_AREGUIWINDOW_HEIGHT: 1080,
	MODELGUI_ACSVERSION: 'webACS_v0.1_to_be_replaced_by_proper_version_number'
}