<?xml version="1.0"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" modelName="29.07.2014_1130" version="20130320">
    <modelDescription>
        <shortDescription>das ist die short description</shortDescription>
        <requirements>das sind die model requirements</requirements>
        <description>das ist eine detaillierte description</description>
    </modelDescription>
    <components>
        <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
            <description>Keyboard which sends event after button press</description>
            <properties></properties>
            <layout>
                <posX>226</posX>
                <posY>293</posY>
            </layout>
            <gui>
                <posX>0</posX>
                <posY>444</posY>
                <width>500</width>
                <height>2000</height>
            </gui>
        </component>
    </components>
    <channels></channels>
    <eventChannels></eventChannels>
    <modelGUI>
        <Decoration>true</Decoration>
        <Fullscreen>false</Fullscreen>
        <AlwaysOnTop>false</AlwaysOnTop>
        <ToSystemTray>false</ToSystemTray>
        <ShopControlPanel>true</ShopControlPanel>
        <AREGUIWindow>
            <posX>0</posX>
            <posY>0</posY>
            <width>9000</width>
            <height>5000</height>
        </AREGUIWindow>
    </modelGUI>
</model>